/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BuyCatalogueRouteImport } from './routes/buy.catalogue'
import { Route as BuyOrdersRouteImport } from './routes/buy.orders'
import { Route as SellListingsRouteImport } from './routes/sell.listings'
import { Route as SellOrdersRouteImport } from './routes/sell.orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCatalogueRoute = BuyCatalogueRouteImport.update({
  id: '/buy/catalogue',
  path: '/buy/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyOrdersRoute = BuyOrdersRouteImport.update({
  id: '/buy/orders',
  path: '/buy/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellListingsRoute = SellListingsRouteImport.update({
  id: '/sell/listings',
  path: '/sell/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellOrdersRoute = SellOrdersRouteImport.update({
  id: '/sell/orders',
  path: '/sell/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/buy/catalogue': typeof BuyCatalogueRoute
  '/buy/orders': typeof BuyOrdersRoute
  '/sell/listings': typeof SellListingsRoute
  '/sell/orders': typeof SellOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/buy/catalogue': typeof BuyCatalogueRoute
  '/buy/orders': typeof BuyOrdersRoute
  '/sell/listings': typeof SellListingsRoute
  '/sell/orders': typeof SellOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/buy/catalogue': typeof BuyCatalogueRoute
  '/buy/orders': typeof BuyOrdersRoute
  '/sell/listings': typeof SellListingsRoute
  '/sell/orders': typeof SellOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/buy/catalogue'
    | '/buy/orders'
    | '/sell/listings'
    | '/sell/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/buy/catalogue'
    | '/buy/orders'
    | '/sell/listings'
    | '/sell/orders'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/buy/catalogue'
    | '/buy/orders'
    | '/sell/listings'
    | '/sell/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRoute
  InventoryRoute: typeof InventoryRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  BuyCatalogueRoute: typeof BuyCatalogueRoute
  BuyOrdersRoute: typeof BuyOrdersRoute
  SellListingsRoute: typeof SellListingsRoute
  SellOrdersRoute: typeof SellOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/catalogue': {
      id: '/buy/catalogue'
      path: '/buy/catalogue'
      fullPath: '/buy/catalogue'
      preLoaderRoute: typeof BuyCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/orders': {
      id: '/buy/orders'
      path: '/buy/orders'
      fullPath: '/buy/orders'
      preLoaderRoute: typeof BuyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/listings': {
      id: '/sell/listings'
      path: '/sell/listings'
      fullPath: '/sell/listings'
      preLoaderRoute: typeof SellListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/orders': {
      id: '/sell/orders'
      path: '/sell/orders'
      fullPath: '/sell/orders'
      preLoaderRoute: typeof SellOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRoute,
  InventoryRoute: InventoryRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  BuyCatalogueRoute: BuyCatalogueRoute,
  BuyOrdersRoute: BuyOrdersRoute,
  SellListingsRoute: SellListingsRoute,
  SellOrdersRoute: SellOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
