import type {
  ApplicationReview,
  AdminListingReview,
  AdminPriceReview,
  PaymentFinanceDetail,
  DispatcherDeliveryDetail,
  DispatcherRider,
  OrderInvestigation,
  AuditEventDetail,
} from "@sokoni-digital/domain";
export const operator = { id: "demo-operator", name: "Demo operator" };
export const now = () => new Date().toISOString();
const createdAt = now();
export const market = { id: "demo-market", name: "Demo Central Market" };
export function createFixtures() {
  const applications: ApplicationReview[] = (["vendor", "rider"] as const).map((type) => ({
    id: `demo-${type}`,
    type,
    status: "pending_review",
    version: 1,
    userId: null,
    applicantName: type === "vendor" ? "Demo Produce Stall" : "Demo Rider Applicant",
    phone: "Demo phone",
    phoneVerified: true,
    details: {
      profile: {
        name: type === "vendor" ? "Demo Produce Stall" : "Demo Rider Applicant",
        location: "Demo market",
      },
    },
    market,
    submittedAt: createdAt,
    reviewStartedAt: null,
    reviewerId: null,
    reviewerName: null,
    reason: null,
    issues: [],
    missingRequirements: [],
    documents: [],
    timeline: [],
  }));
  const listings: AdminListingReview[] = ["Beans", "Tomatoes"].map((name, i) => ({
    id: `demo-listing-${i}`,
    catalogProductId: `demo-product-${i}`,
    productName: name,
    categoryName: "Produce",
    packageQuantity: 1,
    packageUnit: "kg",
    description: "Fictional sample produce",
    approvedPriceUgx: 4000,
    status: "pending_approval",
    availability: "available",
    version: 1,
    updatedAt: createdAt,
    images: [],
    latestPriceRequest: null,
    sellerId: "demo-vendor",
    vendorName: "Demo Produce Stall",
    marketName: market.name,
    submittedAt: createdAt,
    priceHistory: [],
    auditHistory: [],
  }));
  const prices: AdminPriceReview[] = [
    {
      requestId: "demo-price",
      listingId: listings[0].id,
      productName: "Beans",
      vendorName: "Demo Produce Stall",
      currentPriceUgx: 4000,
      proposedPriceUgx: 4500,
      reason: "Sample seasonal adjustment",
      createdAt,
      packageQuantity: 1,
      packageUnit: "kg",
      marketName: market.name,
      images: [],
      percentageChange: 12.5,
      largePriceChange: false,
      recentUnavailableChanges: 0,
      auditHistory: [],
    },
  ];
  const payments: PaymentFinanceDetail[] = ["failed", "successful", "pending"].map((status, i) => ({
    id: `demo-payment-${i}`,
    version: 1,
    checkoutId: `demo-checkout-${i}`,
    reference: `DEMO-ORD-${i + 1}`,
    provider: "pesapal",
    status,
    amount: 13000,
    currency: "UGX",
    merchantReference: `DEMO-PAY-${i + 1}`,
    providerReference: null,
    createdAt,
    reconciliations: [],
    providerEvents: [],
    investigations: [],
    refunds: [],
  }));
  const riders: DispatcherRider[] = [
    {
      id: "demo-rider",
      displayName: "Demo Rider",
      availability: "available",
      locationIsFresh: true,
      locationReceivedAt: createdAt,
      distanceKm: 1.2,
      lastLocation: {
        latitude: 0.31,
        longitude: 32.58,
        accuracyMeters: 10,
        capturedAt: createdAt,
        receivedAt: createdAt,
      },
    },
  ];
  const deliveries: DispatcherDeliveryDetail[] = ["unassigned", "in_transit"].map((status, i) => ({
    delivery: {
      id: `demo-delivery-${i}`,
      reference: `DEMO-DL-${i + 1}`,
      status: status as "unassigned" | "in_transit",
      version: 1,
      feeUgx: 3000,
      assignedAt: i ? createdAt : null,
      completedAt: null,
      scheduledFor: null,
      createdAt,
      updatedAt: createdAt,
      market,
      destination: {
        label: "Demo destination",
        summary: "Sample Kampala address",
        zoneName: "Central",
      },
    },
    order: {
      id: `demo-order-${i}`,
      reference: `DEMO-ORD-${i + 1}`,
      status: "confirmed",
      currency: "UGX",
      itemsSubtotal: 10000,
      deliveryFee: 3000,
      serviceFee: 0,
      total: 13000,
      createdAt,
      updatedAt: createdAt,
    },
    vendors: [
      {
        vendor: { id: "demo-vendor", name: "Demo Produce Stall" },
        sellerOrder: {
          id: `demo-seller-order-${i}`,
          reference: `DEMO-SO-${i}`,
          status: "ready_for_pickup",
          version: 1,
          subtotal: 10000,
        },
        items: [
          {
            id: `demo-item-${i}`,
            productName: "Beans",
            packageQuantity: 1,
            packageUnit: "kg",
            unitPrice: 5000,
            quantity: 2,
            lineTotal: 10000,
          },
        ],
      },
    ],
    pickups: [],
    assignedRider: i ? riders[0] : null,
    customerPin: {
      configured: true,
      confirmedAt: null,
      expiresAt: null,
      failedAttempts: 0,
      lockedAt: null,
    },
    issues: [],
    assignmentHistory: [],
    evidence: {
      deliveryId: `demo-delivery-${i}`,
      reference: `DEMO-DL-${i + 1}`,
      completedAt: null,
      consumerConfirmedAt: null,
      images: [],
    },
    timeline: [],
  }));
  const orders: OrderInvestigation[] = deliveries.map((d, i) => ({
    order: {
      id: d.order.id,
      reference: d.order.reference,
      status: i ? "confirmed" : "awaiting_payment",
      fulfilmentType: "delivery",
      market,
      pricing: {
        itemsSubtotal: 10000,
        deliveryFee: 3000,
        serviceFee: 0,
        total: 13000,
        currency: "UGX",
      },
      createdAt,
      updatedAt: createdAt,
    },
    consumer: { id: `demo-consumer-${i}`, name: "Demo Customer", phoneMasked: "Demo phone ••••" },
    deliveryAddress: { summary: "Sample Kampala address" },
    payment: {
      id: payments[i].id,
      status: i ? "paid" : "failed",
      amount: 13000,
      currency: "UGX",
      version: 1,
    },
    vendors: d.vendors.map((v) => ({ ...v, vendor: { ...v.vendor, market }, evidence: [] })),
    delivery: {
      id: d.delivery.id,
      reference: d.delivery.reference,
      status: d.delivery.status,
      version: 1,
      rider: i ? { id: "demo-rider", name: "Demo Rider", phoneMasked: "Demo phone ••••" } : null,
      issues: [],
      evidence: [],
    },
    timeline: [],
    notifications: [
      {
        id: `demo-notification-${i}`,
        type: "order.confirmed",
        entityType: "order",
        title: "Demo order update",
        body: "Fictional sample notification",
        priority: "normal",
        createdAt,
        deliveries: [{ channel: "push", status: "simulated", attemptCount: 1 }],
      },
    ],
    refunds: [],
    supportNotes: [],
  }));
  const audit: AuditEventDetail[] = [
    {
      id: "demo-audit",
      actor: { staffId: operator.id, name: operator.name, role: "Demo operator" },
      action: "demo.opened",
      entity: { type: "order", id: orders[0].order.id, reference: orders[0].order.reference },
      reason: "Fictional sample activity",
      operationId: null,
      requestId: null,
      context: { ip: null, device: "Local demo", userAgent: null },
      occurredAt: createdAt,
      previousState: null,
      newState: null,
      details: { simulated: true },
    },
  ];
  return { applications, listings, prices, payments, riders, deliveries, orders, audit };
}
